### ISSUE TITLE
Highlighting Matching Search Results

### ISSUE THREAD

**Issue by craigshannon** [rashidkpc/kibana2#136]
Hi, 

I would like to know if it is possible for Kibana to highlight matching strings in the search results similar to Splunk? After searching about the documentation and the internet, I couldn't see this query being raised, but it seems like a very useful feature to have. Apologies if this is a trivial feature already built in to Kibana. 

Thanks,

Craig.

**Comment by azulcactus** [comment]
I agree, that would be very nice!

**Comment by rashidkpc** [comment]
Possible and not very hard. The challenge would be deciding what to highlight. Can't highlight everywhere, Elasticsearch doesn't do highlighting on _all. Could we just highlight on the user's Default_fields ? Though that would create some amount of confusion when a search returns results where the matched value is not in the default_fields. 

Thoughts?

**Comment by untergeek** [comment]
I would agree.  Whatever fields you have set in KibanaConfig should be the ones to have highlighting.

**Comment by craigshannon** [comment]
I also agree that highlighting only the fields defined within KibanaConfig should be adequate. I had a look in the query.rb code and I think something like the following could help do the trick in the section where the query is put together ~line 53. I'm not sure though how Kibana interprets the replies as this made no difference to the display of the results within the GUI:

 "highlight" => {
      "tag_schema" => "styled",
      "fields" => {
          KibanaConfig::Default_fields => {"pre_tags" => ["<em>"], "post_tags" => ["</em>"] }
          }
       }

**Comment by craigshannon** [comment]
Does anyone know what code would need changed for this to work?

**Comment by craigshannon** [comment]
Has anyone been able to look into a solution for this? Looking at the elasticsearch docs this should be simple enough, but I think that the Kibana CSS might be doing something on top of the results that are returned?

**Comment by rashidkpc** [comment]
I've tried to answer this like 5 times and keep getting pulled away. 

The problem: A lot of folks log XML, so Kibana escapes XML entities, including html tags so that they display correctly (function xmlEnt()). It also inserts invisible word break characters in a, sometimes ineffective, attempt to prevent horizontal scrolling (function wbr()). An unfortunate side effect of dynamic table column widths.

Maybe solution: A custom tag. Could do something like @KIBANA_HIGHLIGHT_START@ and @KIBANA_HIGHLIGHT_END@. This would solve the xmlEnt() issue, but wbr() will need to be updated to not break those tags

Order of operations:
1) Check for highlight field in ES response, if found, use this for the fields that contain highlights
2) Pass to xmlEnt/wbr
3) Replace our custom @@ tags with html tags
4) Use non-highlighted field for the raw span
5) Display highlighted field

**Comment by craigshannon** [comment]
Thanks for the response, I thought that Kibana must have been manipulating the reply from Elasticsearch to strip out the HTML tags. I will try and investigate further now that I know what Kibana is doing in the background. 

Thanks!

**Comment by dav3860** [comment]
I've got it working. I added a "| highlight" keyword to display highlighted results.
But I need to clean up the code and to fix a couple of issues. I make a pull request when possible.

**Comment by dav3860** [comment]
Still needs to add a working " | highlight @field" keyword. But work needs to be done on the "pipe" mechanism.

**Comment by craigshannon** [comment]
Thanks, this will be very useful!
