### ISSUE TITLE
several issue and inquiry about Kibana3

### ISSUE THREAD

**Issue by cksjackey** [rashidkpc/kibana2#368]
Hi All,

I would like to ask the following issue. Currently my deployment is syslog-ng > redis > logstash > elasticsearch > kibana 3
1. Some logging cannot be show in the field and message area unless I specify the "tags" in the query. For example, my logging system include different brand firewall such as FortiGate, netscreen, srx. When I look at @tags, I do not find any related to srx unless I type @tags:"srx"
2. Is it possible to generate a chart with customize x-axis for histogram?
3.  Any document about the query syntax or it is based on elasticsearch or other product?
4. Similar to question 3, I would like to query the top talker. For example, filter top 10 source IP address so I could use the pie to check the interest information.

Many thanks.

Rgds,
Jacky

**Comment by rashidkpc** [comment]
1. I'm not sure what the issue is with your @tags, might want to ask in the logstash channel on freenode
2. no
3. Query syntax is Lucene query string syntax, there is a primer on it at http://three.kibana.org/about.html
4. Find me in #logstash on freenode, I'm not completely sure what you're looking to do here.

Also, please submit Kibana 3 issue in the appropriate repo:
https://github.com/elasticsearch/kibana
