### ISSUE TITLE
No output in Stream at all

### ISSUE THREAD

**Issue by drablo** [rashidkpc/kibana2#73]
I'm experiencing stream problems while there are no errors in logs. I keep receiving log messages from servers and all is OK except of that the stream page is completely empty.

Here's what I get when I switch the "stream" from 'Play' to 'Pause':

MY.IP - - [18/Sep/2012 11:06:33] "GET /api/stream/eyJzZWFyY2giOiIiLCJmaWVsZHMiOlsiQG1lc3NhZ2UiXSwib2Zmc2V0IjowLCJ0aW1lZnJhbWUiOjkwMCwiZ3JhcGhtb2RlIjoiY291bnQifQ== HTTP/1.1" 200 - 0.0108
MY.IP - - [18/Sep/2012:11:06:33 CEST] "GET /api/stream/eyJzZWFyY2giOiIiLCJmaWVsZHMiOlsiQG1lc3NhZ2UiXSwib2Zmc2V0IjowLCJ0aW1lZnJhbWUiOjkwMCwiZ3JhcGhtb2RlIjoiY291bnQifQ== HTTP/1.1" 200 0

When I restart kibana I also get errors which have been described in issue number 68, over here:
https://github.com/rashidkpc/Kibana/issues/68
at the beginning (when I do kibana + elasticsearch restart) but they dissapear as soon as everything is online. 

Update: I use the kibana-ruby latest-version branch from https://github.com/rashidkpc/Kibana.git

**Comment by rashidkpc** [comment]
Haven't been able to reproduce this, though I did fix a but that affected streaming in IE today that could have been the cause. Going to close for now, if this is still happening with the latest version please reopen with your browser/ruby version

Thanks

**Comment by dkowis** [comment]
I can reproduce it. No errors though.

Ruby 1.9.3p286 Firefox browser on the linux.

Nothing is displayed, and I just see a request every 10 seconds in the sinatra logs. I do see log entries showing up when I search for it, so they're getting into elastic, just not onto the stream.

Perhaps it's because my logstash index is 

```
output {
  elasticsearch {
    cluster => 'logstash'
    embedded => false
    index => "logstash-%{+YYYY.MM}"
  }
}
```

I have in Kibana/KibanaConfig.rb

```
  Smart_index = true
  Smart_index_pattern = 'logstash-%Y.%m'
```

That should be correct as I understand it.

**Comment by emadum** [comment]
Made some progress since I initially posted this comment, and the information I included was irrelevant. Turned out it is an issue involving timezones. My data is getting indexed into ES with timestamps that are 3 hours behind the actual time. Still haven't figured out why; but modifying the code for the /api/stream request in kibana.rb to look 3 hours in the past causes the stream to work. I should add that changing the Timezone setting in KibanaConfig.rb had no effect on the times being used to query ES in /api/stream.

It is likely that others experiencing this issue have a similar time mismatch problem.
