### ISSUE TITLE
Kibana doesn't display any events nor graphs in Safari

### ISSUE THREAD

**Issue by macbar** [rashidkpc/kibana2#86]
Hi, I was struggling to get kibana (the ruby branch) working, as I didn't see any events pop up.
I just noticed it is working OK in Chrome, so it's probably nothing to do with the Kibana/ES setup.

**Comment by rashidkpc** [comment]
What version of Kibana and Safari? I just loaded up the latest commit to the kibana-ruby branch in Safari 6.0 (7536.25) and things seem to look ok

**Comment by macbar** [comment]
On 28 Sep 2012, at 15:11, Rashid Khan notifications@github.com wrote:

> What version of Kibana and Safari? I just loaded up the latest commit to the kibana-ruby branch in Safari 6.0 (7536.25) and things seem to look ok
> 
> kibana-ruby branch at commit e54ae68bd29a1d02556eee0311925c2140f14869
> Safari Version 6.0 (8536.25) (mountain lion)

Screenshot at http://cl.ly/image/0T3b1V303S36

Thanks,
Pieter.

**Comment by rashidkpc** [comment]
Was able to reproduce. Issue with date parsing, sort of surprised that didn't show itself in older versions of Safari, odd. Fixed.

**Comment by macbar** [comment]
Super, thanks!

Pieter.

Op 30-sep.-2012 om 00:33 heeft Rashid Khan notifications@github.com het volgende geschreven:

**Comment by macbar** [comment]
Hmm, I still get the 'invalid date' error...

**Comment by rashidkpc** [comment]
Tested on 6.0.1 on Mountain Lion, not able to replicate.

**Comment by khobbits** [comment]
Thought you might want a few details.
https://www.evernote.com/shard/s18/sh/be08a4b6-c225-47b0-bd1e-318bf53eb240/8c61b29b76a96339fdc551883f6e81b3
Ever since I added json Apache logging to Logstash, Safari is unable to open log entries on Kibana, it seems that Safari can't handle the Apache timestamp.
Works fine in other browsers, investigation shows that it is caused by the UTC offset (+0100).

Posts on stack overflow suggested that Safari doesn't support '+0100' only '+01:00'.
